#Config Database
[Database]
Stringconnection = "mongodb://root:root@10.1.0.4:27017/"
NAME_DATABASE = "bet_store"

#Config secretkey auth 
[Auth]
Secretkey = "hsoVvtJfWavHIhmOkBp98u4qrR1w73SIG90FUq1H7YerUpgU5GD9gAnoGMr6kWQKlgLHAKJNfDbkJRlTiZwaxK5B5pEf0FlBpNF5RFxASHa0V4_vFJn0K7HrCCzvESlm0LcGJmaTiV_jPlHCOU1xwlxsQLvLUwL__GxR2PkiFzhF2K4PAoDcMiD4ojPZgEUsEeKvtf7NHiD3P7_Cw0fYOetbWW5irwiAQtxZpqZSwN-wy7zIwLsbjzZbyUgMmUpcNrObJo_j9Hn_Tv0-cPfBKek-qQzu79VzaByX9rDFyhc6Z1plAGUb3w2c_qkLitnyWi2X0ATZv8TVkxDRFiwj2Q"
Issuer = "localhost"

#Config tel auth server
[TelAuthServer]
AUTH_KEY = "QUM4Y2NiYmE4ZmM5YjliMDVlYWQ4YWM4MzFmNmVkNTk0NToxYjhiZmY0Mjg4ZjdhNjA0ZWI1Zjk3OWI3Yjk5ZDJkYg=="
TEL_HOST = "+12053862330"
URL_HOST = "https://api.twilio.com/2010-04-01/Accounts/AC8ccbba8fc9b9b05ead8ac831f6ed5945/Messages.json"